---
- include_tasks:        '../tasks/dependencies.yml'
- include_tasks:        '../tasks/install_packages.yml'
- include_tasks:        '../tasks/add_users_to_groups.yml'
- include_tasks:        '../tasks/sync_dirs.yml'
- include_tasks:        '../tasks/enable_services.yml'
  when:                 install_packages_result.changed
- include_tasks:        '../tasks/start_services.yml'
  when:                 install_packages_result.changed
- include_tasks:        '../tasks/restart_services.yml'
  when:                 sync_dirs_result.changed
                        or add_users_to_groups_result.changed
